stages:
  prepare_data:
    cmd: python src/prepare_data.py --config=params.yaml
    deps:
    - datasets/raw/images
    - datasets/raw/labels
    - src/prepare_data.py
    - params.yaml
    outs:
    - datasets/prepared/train
    - datasets/prepared/test
    - datasets/prepared/val
  train:
    cmd: python src/train.py --config=params.yaml
    deps:
    - datasets/prepared/train
    - datasets/prepared/val
    - datasets/prepared/test
    - src/train.py
    - src/yolov8s.pt
    - params.yaml
    outs:
    - face_detection_model
  
  
