name: CML CI/CD for Github and AWS Sagemaker


on:
    push:
        branches:
            - train
    # pull_request:
    #     branches:
    #         - main
### First Define the env variables needed in the code

### Jobs to Run
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repo at $GITHUB_WORKFSPACE
      - uses: actions/checkout@v3
      # Setup CML and DVC
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      # Setup Python 3.10
      - name: Python 3.10 setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
      - name: Install the dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run DVC Pipeline - Prepare and Train Data
        # Pull Data and run cache | Reproduce DVC Pipeline
        run: |
          dvc pull data --run-cache
          dvc repro
      - name: Create CML Reporting
        run : |
         echo "## Metrics: Training and Validation" >> report.md
         echo "98% accuracy in Test Data" >> report.md
        
